<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <AssemblyName>Gym.Logic</AssemblyName>
	  <RootNamespace>Gym.Logic</RootNamespace>
	  <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infra\Infra.csproj" />
  </ItemGroup>


</Project>
